### ISSUE TITLE
Additional Info - Synology

### ISSUE THREAD

**Issue by Wh1terat** [cyrozap/jmb58x-re#4]
You may already be aware, but Synology use the JMB585 in some of their products - they also kindly provide semi commented source for some of their own libraries that interact with it (including methods to update the flash).

Someone has kindly hosted it on GH:
https://github.com/moetayuko/linux_dsm_epyc7002/

As your repo is the leading source of data for the JMB58x, I thought you might be interested.

I also have the following files should you wish to host them on here.

| Document             | Chip   | Document No. | Revision | Date       |
|----------------------|--------|--------------|----------|------------|
| DATASHEET            | JMB585 | PDS-18001    | 2.01     | 01/14/2020 |
| PCB LAYOUT GUIDE     | JMB585 | LOG-18001    | 1.3      | 04/24/2019 |
| SPI SUPPORT LIST     | JMB585 | SPI-18003    | 1.00     | 10/17/2018 |

Additionally I have the schematic and PCB design files for the JMB585 reference board (JMB585-DB-02-01)

**Comment by cyrozap** [comment]
> You may already be aware, but Synology use the JMB585 in some of their products - they also kindly provide semi commented source for some of their own libraries that interact with it (including methods to update the flash).
> 
> Someone has kindly hosted it on GH: https://github.com/moetayuko/linux_dsm_epyc7002/
> 
> As your repo is the leading source of data for the JMB58x, I thought you might be interested.

Thank you, I wasn't aware of this at all.

Synology's modifications to [drivers/ata/ahci.c](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c) have been incredibly illuminating. For instance, the file lists the addresses of the internal registers that configure [the amplifiers](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1085-L1087), [CTLE (Continuous Time Linear Equalization)](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1088), and [SSC (Spread Spectrum Clocking)](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1089) of the SATA PHY, as well as [some addresses that can be used to determine the chip revision](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1272-L1279). It also explains [the function of bit 18 in the internal register addresses](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1100-L1102), [the function of one of the unknown SPI register bits](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1174), and [how to parse the version of the SPI flash image](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1199-L1254). It even explains [how to configure and access the GPIO pins](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1633-L1682) (with what looks like a bug [here](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1663) unless it's [the documentation](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/drivers/ata/ahci.c#L1639-L1640) that's wrong).

While the [SPI updating code](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_jmb585_update_spi.c) didn't tell me much more than I already knew, I did learn that [the device ID in the flash image header can be either 0x0585 or 0x0582](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_jmb585_update_spi.c#L138-L142). All the JMB58x devices I have, including one JMB582 card, have their device IDs set to 0x0585, so I'll have to test with 0x0582 sometime to confirm if it also works with those cards.

Finally, it seems [lib/synolib/syno_sata_signal_check.c](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_sata_signal_check.c) also lists [some interesting internal PCIe PHY registers](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_sata_signal_check.c#L47-L56) and [lib/synolib/syno_sata_signal_test.c](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_sata_signal_test.c) shows [how to parse the SATA PHY amplifier configuration values](https://github.com/moetayuko/linux_dsm_epyc7002/blob/bda8b4efec7bc442822e2abbffafa13522e9b248/lib/synolib/syno_sata_signal_test.c#L831-L832).

What a great resource, thanks again!

> I also have the following files should you wish to host them on here.
> 
> Document	Chip	Document No.	Revision	Date
> DATASHEET	JMB585	PDS-18001	2.01	01/14/2020
> PCB LAYOUT GUIDE	JMB585	LOG-18001	1.3	04/24/2019
> SPI SUPPORT LIST	JMB585	SPI-18003	1.00	10/17/2018
> 
> Additionally I have the schematic and PCB design files for the JMB585 reference board (JMB585-DB-02-01)

I can't host those documents, or any other proprietary material, in this repository. Everything in this repo must be freely-licensed, both to ensure that users have the freedom to access, redistribute, and modify it and to avoid any copyright infringement (and the potential takedowns and liability associated with that).
